ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.18.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.9.1]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: [--fix, --show-fixes]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks
